apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api-dev
  labels:
    app: hello-world-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-api
      env: dev
  template:
    metadata:
      labels:
        app: hello-world-api
        env: dev
    spec:
      containers:
      - name: hello-world-api
        image: rachana.azurecr.io/devopsassessment:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-dev
  labels:
    app: hello-world-api
    env: dev
spec:
  selector:
    app: hello-world-api
    env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP